version: "2"

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    ports:
      - "9091:90"
    links:
      - node
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
    - ./:/var/www
    tty: true
    ports:
    - "9090:9090"
  postgres:
        image: postgres
        build:
          context: ./
          dockerfile: docker/postgres.docker
        volumes:
          - ./storage/pgsql:/var/lib/postgresql/data
        environment:
          - "POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}"
          - "POSTGRES_USER=${DB_USERNAME}"
          - "POSTGRES_PASSWORD=${DB_PASSWORD}"
          - "POSTGRES_DB=${DB_DATABASE}"
          - "POSTGRES_DATABASE=${DB_DATABASE}"
          - "POSTGRES_DBUSER=${DB_USERNAME}"
          - "POSTGRES_DBPASS=${DB_PASSWORD}"
          - "PGDATA=/var/lib/postgresql/data"
        ports:
          - 54321:5432
